name: Bot RU Russas

on:
  schedule:
    - cron: '0 12 * * 1-5' 
  workflow_dispatch: 

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: pip install requests beautifulsoup4

      - name: Executar Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot_cardapio.py 